// List of link types
const BA = "Bande-annonce";
const RE = "Résumé";

// Work list
module.exports = {

    doublages: [{
        title: "The Eminence in Shadow",
        description: "",
        date: "2023",
        type: "Animé/Shonen",
        labo: "Timeline Factory",
        diffusion: "",
        link: "https://www.allocine.fr/video/player_gen_cmedia=19598627&cserie=32923.html",
        type_link: BA,
        affiche: "the_eminence_in_shadow",
    }, {
        title: "Lookism",
        description: "",
        date: "2022",
        type: "Animé/Sitcom",
        labo: "VSI",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=m7JDgO2pqHc&ab_channel=NetflixFrance",
        type_link: BA,
        affiche: "lookism",
    }, {
        title: "iCarly",
        description: "",
        date: "2021-2023",
        type: "Sitcom",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=yUM8OvngsIE&ab_channel=erukurawjin",
        type_link: BA,
        affiche: "icarly",
    }, {
        title: "Cochon Chèvre Banane Criquet",
        description: "",
        date: "2022",
        type: "Cartoon",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=dEJ84ULSsOE&list=PLwLVa1RYGXSRyIrIG9UeQadm5KxrGgxSw&ab_channel=NickelodeonFrance",
        type_link: BA,
        affiche: "pig_goat_banana_cricket",
    }, {
        title: "Bee et Puppycat",
        description: "",
        date: "2022",
        type: "Dessin animé",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=mX1IQn5FqJ4&ab_channel=CartoonHangover",
        type_link: BA,
        affiche: "bee_and_puppycat",
    },{
        title: "Big Mouth",
        description: "",
        date: "2022",
        type: "Kdrama/Thriller",
        labo: "Dubbing Brothers",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=Z3OMssCwMjA&ab_channel=KdramaZone",
        type_link: BA,
        affiche: "big_mouth",
    },{
        title: "Voisins mais pas trop",
        description: "",
        date: "2022",
        type: "Sitcom",
        labo: "Eclair VOA",
        diffusion: "",
        link: "https://www.allocine.fr/series/ficheserie_gen_cserie=23219.html",
        type_link: BA,
        affiche: "voisins_mais_pas_trop",
    },{
        title: "Dragon Quest : La Quête de Daï",
        description: "",
        date: "2022",
        type: "Animé/Shonen",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=ZT14d5S9U0k&ab_channel=BastienDruker",
        type_link: BA,
        affiche: "the_adventure_of_dai",
    },{
        title: "La légende de Spark",
        description: "",
        date: "2021",
        type: "Animé jeunesse",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=-QrDLZYsPzQ&ab_channel=CanalJ",
        type_link: BA,
        affiche: "la_legende_de_spark",
    },{
        title: "Oshi No Ko",
        description: "",
        date: "2023",
        type: "Animé/Shonen",
        labo: "ADN",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=ijxs5m4EmiM&ab_channel=ADN-AnimationDigitalNetwork",
        type_link: BA,
        affiche: "oshi_no_ko",
    },{
        title: "Malum",
        description: "",
        date: "2023",
        type: "Film d'horreur",
        labo: "Cinéma",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=AuZ10zYOYnY&t=30s&ab_channel=KinepolisBelgique",
        type_link: BA,
        affiche: "malum",
    },],

    sous_titrages: [{
        title: "Evil",
        description: "",
        date: "2022-2023",
        type: "Policier/Paranormal",
        labo: "Libra Videaudi",
        diffusion: "",
        link: "https://www.allocine.fr/video/player_gen_cmedia=19596732&cserie=24644.html",
        type_link: BA,
        affiche: "evil",
    },{
        title: "Tales of Symphonia (remaster)",
        description: "",
        date: "2023",
        type: "Animé/Shonen",
        labo: "Keywords studios",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=Wo3hfxFp8mM&t=670s&ab_channel=BANDAINAMCOEurope",
        type_link: BA,
        affiche: "tales_of_symphonia",
    },{
        title: "La folle aventure des Durrells",
        description: "",
        date: "2022",
        type: "Série biographique",
        labo: "Titrafilm",
        diffusion: "",
        link: "https://www.allocine.fr/series/ficheserie_gen_cserie=19667.html",
        type_link: BA,
        affiche: "the_durrells",
    },{
        title: "All the food in the world",
        description: "",
        date: "2022",
        type: "Documentaire/ Divertissement",
        labo: "Libra Videaudi",
        diffusion: "",
        link: "https://www.6play.fr/all-the-food-in-all-the-world-p_21860",
        type_link: BA,
        affiche: "all_the_food_in_the_world",
    },{
        title: "Clique X Ronnie Fieg",
        description: "",
        date: "2021",
        type: "Interview",
        labo: "Première fois prod",
        diffusion: "",
        link: "https://www.youtube.com/watch?time_continue=400&v=X1paJFwA1m8&embeds_euri=https%3A%2F%2Fwww.google.com%2F&source_ve_path=Mjg2NjY&feature=emb_logo&ab_channel=CliqueTV",
        type_link: BA,
        affiche: "clique",
    },{
        title: "Glow Up - Nouvelle-Zélande",
        description: "",
        date: "2023",
        type: "Concours maquillage",
        labo: "6Play",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=lIu8Rmu4Hrw&ab_channel=GlowUp",
        type_link: BA,
        affiche: "glow_up",
    },{
        title: "30 ans et déjà grands-parents",
        description: "",
        date: "2023",
        type: "Documentaire",
        labo: "6Play",
        diffusion: "",
        link: "30 ans et déjà grands-parents",
        type_link: BA,
        affiche: "30_ans",
    },],

    voice_over: [{
        title: "The Challenge",
        description: "",
        date: "2021-2022",
        type: "Divertissement/TV réalité",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=44q2SxttEy0&ab_channel=MTV%27sTheChallenge",
        type_link: BA,
        affiche: "the_challenge",
    },{
        title: "Sale Boulots",
        description: "",
        date: "2022",
        type: "Documentaire",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.imdb.com/title/tt0458259/",
        type_link: BA,
        affiche: "dirty_jobs",
    },{
        title: "16 ans et dépendants",
        description: "",
        date: "2021",
        type: "Documentaire",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.imdb.com/title/tt13030424/",
        type_link: BA,
        affiche: "16_and_recovering",
    },{
        title: "True Life Crime UK/US",
        description: "",
        date: "2022",
        type: "Divertissement/Policier",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.imdb.com/title/tt14797600/",
        type_link: BA,
        affiche: "true_life_crime",
    },{
        title: "MTV Cribs",
        description: "",
        date: "2022",
        type: "Divertissement",
        labo: "Lylo",
        diffusion: "",
        link: "https://www.imdb.com/title/tt0276656/",
        type_link: BA,
        affiche: "mtv_cribs",
    },{
        title: "Mon voisin, ce tueur",
        description: "",
        date: "2022",
        type: "Divertissement/Thriller",
        labo: "VDM",
        diffusion: "",
        link: "https://www.dailymotion.com/video/x8is0o3",
        type_link: BA,
        affiche: "fear_thy_neighbour",
    },{
        title: "Retour à l’instinct primaire : le choc des légendes",
        description: "",
        date: "2023",
        type: "TV réalité/survie",
        labo: "Discovery",
        diffusion: "",
        link: "https://www.dailymotion.com/video/x8lmdao",
        type_link: BA,
        affiche: "last_one_standing",
    },],

    jeux_video: [{
        title: "Immortality",
        description: "",
        date: "2022",
        type: "Enquête/Épouvante",
        labo: "Lionbridge",
        diffusion: "",
        link: "https://www.gamekult.com/jeux/project-a-3050882495.html",
        type_link: BA,
        affiche: "immortality",
    },{
        title: "Relayer",
        description: "",
        date: "2022",
        type: "Méca/Stratégie/RPG",
        labo: "Lionbridge",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=59u6R8DUz1E&ab_channel=PlayStation",
        type_link: BA,
        affiche: "relayer",
    },{
        title: "Sword Art Online : Integral Factor",
        description: "",
        date: "2022",
        type: "MMORPG",
        labo: "Keywords studios",
        diffusion: "",
        link: "https://www.gamekult.com/jeux/sword-art-online-integral-factor-3050876799.html",
        type_link: BA,
        affiche: "sao_integral_factor",
    },{
        title: "Starfield",
        description: "",
        date: "2023",
        type: "FPS / Sci-fi",
        labo: "Bethdesda",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=Y76r88x-TSI&ab_channel=BethesdaSoftworksFR",
        type_link: BA,
        affiche: "starfield",
    },{
        title: "The Rumble Fish 2",
        description: "",
        date: "2023",
        type: "Jeu de combat",
        labo: "Sammy / Sega",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=dEk_4wbVhJ4&ab_channel=GameTrailers",
        type_link: BA,
        affiche: "the_rumble_fish_2",
    },],

    sme: [{
        title: "L'invitation",
        description: "",
        date: "2022",
        type: "Thriller psychologique",
        labo: "Titrafilm",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=9hFcsJv5ybs&ab_channel=FredGrivois",
        type_link: BA,
        affiche: "invitation",
    },{
        title: "Mayans M.C.",
        description: "",
        date: "2021",
        type: "Divertissement/Série d'action",
        labo: "VDM",
        diffusion: "",
        link: "https://www.youtube.com/watch?v=V1PEgoOrPM0&ab_channel=FXNetworks",
        type_link: BA,
        affiche: "mayans_mc",
    },{
        title: "The Beast Must Die",
        description: "",
        date: "2021",
        type: "Drame/Thriller",
        labo: "VDM",
        diffusion: "",
        link: "https://www.imdb.com/title/tt9062784/",
        type_link: BA,
        affiche: "the_beast_must_die",
    },{
        title: "L'apocalypse du grain de blé",
        description: "",
        date: "2022",
        type: "Documentaire",
        labo: "Titrafilm",
        diffusion: "",
        link: "",
        type_link: BA,
        affiche: "apocalypse_grain_de_ble",
    },],
}