// List of link types
const BA = "Bande-annonce";
const RE = "Résumé";

// Work list
module.exports = {

    doublages: [{
        title: "Lookism",
        description: "Script FR de deux épisodes de la série",
        date: "2022",
        type: "Anime",
        labo: "VSI",
        diffusion: "Netflix",
        link: "https://www.google.com/",
        type_link: BA,
        affiche: "imgDoublage1",
    }, {
        title: "Pig Goat Banana Cricket",
        description: "Script FR épisodes 1 et 2 dqzhdnbyhzqdh zuyqhd uzqhd uzhu dhzu dzud z huz hu zhuzh uefe",
        date: "2023",
        type: "Cartoon",
        labo: "VSI",
        diffusion: "nickelodeon",
        link: "https://www.google.com/",
        type_link: RE,
        affiche: "PigGoatBananaCricket",
    }, {
        title: "Lookism",
        description: "Script FR de deux épisodes de la série",
        date: "2022",
        type: "Anime",
        labo: "VSI",
        diffusion: "Netflix",
        link: "https://www.google.com/",
        type_link: BA,
        affiche: "imgDoublage1",
    }, {
        title: "Pig Goat Banana Cricket",
        description: "Script FR épisodes 1 et 2 dqzhdnbyhzqdh zuyqhd uzqhd uzhu dhzu dzud z huz hu zhuzh uefe",
        date: "2023",
        type: "Cartoon",
        labo: "VSI",
        diffusion: "nickelodeon",
        link: "https://www.google.com/",
        type_link: RE,
        affiche: "PigGoatBananaCricket",
    },],

    sous_titrages: [{
        title: "Lookism",
        description: "Script FR de deux épisodes de la série",
        date: "2022",
        type: "Anime",
        labo: "VSI",
        diffusion: "Netflix",
        link: "https://www.google.com/",
        type_link: BA,
        affiche: "imgDoublage1",
    }, {
        title: "Pig Goat Banana Cricket",
        description: "Script FR épisodes 1 et 2 dqzhdnbyhzqdh zuyqhd uzqhd uzhu dhzu dzud z huz hu zhuzh uefe",
        date: "2023",
        type: "Cartoon",
        labo: "VSI",
        diffusion: "nickelodeon",
        link: "https://www.google.com/",
        type_link: RE,
        affiche: "PigGoatBananaCricket",
    },],

    voice_over: [{
        title: "Lookism",
        description: "Script FR de deux épisodes de la série",
        date: "2022",
        type: "Anime",
        labo: "VSI",
        diffusion: "Netflix",
        link: "https://www.google.com/",
        type_link: BA,
        affiche: "imgDoublage1",
    }, {
        title: "Pig Goat Banana Cricket",
        description: "Script FR épisodes 1 et 2 dqzhdnbyhzqdh zuyqhd uzqhd uzhu dhzu dzud z huz hu zhuzh uefe",
        date: "2023",
        type: "Cartoon",
        labo: "VSI",
        diffusion: "nickelodeon",
        link: "https://www.google.com/",
        type_link: RE,
        affiche: "PigGoatBananaCricket",
    },],

    jeux_video: [{
        title: "Lookism",
        description: "Script FR de deux épisodes de la série",
        date: "2022",
        type: "Anime",
        labo: "VSI",
        diffusion: "Netflix",
        link: "https://www.google.com/",
        type_link: BA,
        affiche: "imgDoublage1",
    }, {
        title: "Pig Goat Banana Cricket",
        description: "Script FR épisodes 1 et 2 dqzhdnbyhzqdh zuyqhd uzqhd uzhu dhzu dzud z huz hu zhuzh uefe",
        date: "2023",
        type: "Cartoon",
        labo: "VSI",
        diffusion: "nickelodeon",
        link: "https://www.google.com/",
        type_link: RE,
        affiche: "PigGoatBananaCricket",
    },],

    sme: [{
        title: "Lookism",
        description: "Script FR de deux épisodes de la série",
        date: "2022",
        type: "Anime",
        labo: "VSI",
        diffusion: "Netflix",
        link: "https://www.google.com/",
        type_link: BA,
        affiche: "imgDoublage1",
    }, {
        title: "Pig Goat Banana Cricket",
        description: "Script FR épisodes 1 et 2 dqzhdnbyhzqdh zuyqhd uzqhd uzhu dhzu dzud z huz hu zhuzh uefe",
        date: "2023",
        type: "Cartoon",
        labo: "VSI",
        diffusion: "nickelodeon",
        link: "https://www.google.com/",
        type_link: RE,
        affiche: "PigGoatBananaCricket",
    },],
}